package fatec.poo.view;
import fatec.poo.model.QuartoHotel;
import java.text.DecimalFormat;
import java.util.ArrayList;

//@author paula.moraes

public class GuiCadastroQuarto extends javax.swing.JFrame {

    //Creates new form GuiCadastroQuarto
    
    public GuiCadastroQuarto(ArrayList<QuartoHotel> qh) {
        initComponents();
        quartoHotel = qh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNoQuarto = new javax.swing.JLabel();
        jLabelValDiaria = new javax.swing.JLabel();
        txtNoQuarto = new javax.swing.JTextField();
        txtValorDiaria = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Quarto");

        jLabelNoQuarto.setText("No. Quarto");

        jLabelValDiaria.setText("Valor Diária");

        txtValorDiaria.setEnabled(false);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValDiaria)
                            .addComponent(jLabelNoQuarto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtNoQuarto, txtValorDiaria});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoQuarto)
                    .addComponent(txtNoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValDiaria)
                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnSair))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DecimalFormat df = new DecimalFormat("#,##0.00");
        int i;
        for (i = 0; i < quartoHotel.size(); i++){
            if (quartoHotel.get(i) instanceof QuartoHotel){
                if (quartoHotel.get(i).getNumQuarto() == Integer.parseInt(txtNoQuarto.getText())){
                    break;
                }
            }
        }
        
        if (i < quartoHotel.size()){
           posQuarto = i; //localizou o objeto Quarto no ArrayList
        }else{
           posQuarto = -1;//não localizou o objeto Quarto no ArrayList
        }
        
        if (posQuarto >= 0){
            txtNoQuarto.setText(String.valueOf(((QuartoHotel)quartoHotel.get(posQuarto)).getNumQuarto()));
            txtValorDiaria.setText(df.format(((QuartoHotel)quartoHotel.get(posQuarto)).getValorDiaria()));
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
        }else{
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            txtNoQuarto.requestFocus();
        }
        
        txtNoQuarto.setEnabled(false);
        txtValorDiaria.setEnabled(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        q = new QuartoHotel((Integer.parseInt(txtNoQuarto.getText())), 
                                 (Double.parseDouble(txtValorDiaria.getText())));
        quartoHotel.add(q);
        
        txtNoQuarto.setText(null);
        txtValorDiaria.setText(null);
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        
        txtNoQuarto.setEnabled(true);
        txtValorDiaria.setEnabled(false);
        txtNoQuarto.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabelNoQuarto;
    private javax.swing.JLabel jLabelValDiaria;
    private javax.swing.JTextField txtNoQuarto;
    private javax.swing.JTextField txtValorDiaria;
    // End of variables declaration//GEN-END:variables

    private ArrayList<QuartoHotel> quartoHotel;
    private QuartoHotel q = null;
    private int posQuarto;
    
}
